# Update the age recipient below with your own public key (from `age-keygen -y`).
# Example:
#   creation_rules:
#     - path_regex: secrets/.*\.sops\.zsh$
#       age: ["age1yourpublickeyhere"]

creation_rules:
  - path_regex: ^secrets/mac-mekari/dev-secrets\.sops\.zsh$
    age:
      - "age1xewgjv9042k8d89pwnvgttthjjjkxq7vjqnww4yvp60jxyqkvajq8arseg"
  - path_regex: ^secrets/mac-personal/dev-secrets\.sops\.zsh$
    age:
      - "age187j89txmxvg9yw3rv2pcc0yaq7j03gtaxjsdg5cne3xklr6ajv7sx6jl0e"
  - path_regex: ^secrets/mac-personal/gpg-getboon\.sops\.asc$
    age:
      - "age187j89txmxvg9yw3rv2pcc0yaq7j03gtaxjsdg5cne3xklr6ajv7sx6jl0e"
  - path_regex: ^secrets/mac-personal/cloudflare-tunnel-token\.sops\.txt$
    age:
      - "age187j89txmxvg9yw3rv2pcc0yaq7j03gtaxjsdg5cne3xklr6ajv7sx6jl0e"
