# Update the age recipient below with your own public key (from `age-keygen -y`).
# Example:
#   creation_rules:
#     - path_regex: secrets/.*\.sops\.zsh$
#       age: ["age1yourpublickeyhere"]

creation_rules:
  - path: secrets/mac-mekari/dev-secrets.sops.zsh
    age:
      - "age1xewgjv9042k8d89pwnvgttthjjjkxq7vjqnww4yvp60jxyqkvajq8arseg"
  - path: secrets/mac-personal/dev-secrets.sops.zsh
    age:
      - "age1xewgjv9042k8d89pwnvgttthjjjkxq7vjqnww4yvp60jxyqkvajq8arseg"
