version: "0.5"

processes:
  postgres:
    command: postgres -D $PGDATA
    readiness_probe:
      exec:
        command: pg_isready -h localhost -p 5432 -U postgres
      initial_delay_seconds: 2
      period_seconds: 2

  postgres-init:
    command: |
      sleep 3
      if ! psql -h localhost -U postgres -lqt | cut -d \| -f 1 | grep -qw boon_development; then
        echo "Creating boon_development database..."
        createdb -h localhost -U postgres boon_development
        echo "Database created!"
      else
        echo "Database boon_development already exists"
      fi
    depends_on:
      postgres:
        condition: process_healthy
    availability:
      restart: "no"

  valkey:
    command: valkey-server --port 6379
    readiness_probe:
      exec:
        command: valkey-cli ping
      initial_delay_seconds: 1
      period_seconds: 2

  mailpit:
    command: mailpit --smtp 0.0.0.0:1025 --listen 0.0.0.0:8025
    availability:
      restart: on_failure
